<?php
require_once __DIR__ . '/controllers/AuthController.php';
require_once __DIR__ . '/controllers/VentaController.php';
require_once __DIR__ . '/controllers/PerfilController.php';
require_once __DIR__ . '/controllers/UsuarioController.php';
require_once __DIR__ . '/controllers/ClienteController.php';
require_once __DIR__ . '/controllers/ProveedorController.php';
require_once __DIR__ . '/controllers/ProductoController.php';
require_once __DIR__ . '/controllers/CompraController.php';
require_once __DIR__ . '/controllers/InventarioController.php';

require_once __DIR__ . '/controllers/MesaController.php';
require_once __DIR__ . '/controllers/PedidoController.php';
require_once __DIR__ . '/controllers/PlatoController.php';
require_once __DIR__ . '/controllers/CajaController.php';
require_once __DIR__ . '/controllers/PromocionController.php';
require_once __DIR__ . '/controllers/ReporteController.php';

return [
    'login' => [AuthController::class, 'login'],
    'auth/login-empresa' => [AuthController::class, 'loginEmpresa'],
    'clientes/login' => [ClienteController::class, 'login'],
    'clientes/registro' => [ClienteController::class, 'registro'],
    'clientes/verificar-usuario' => [ClienteController::class, 'verificarUsuario'],
    'clientes/logout' => [ClienteController::class, 'logout'],
    'ventas/registrar' => [VentaController::class, 'registrar'],
    'ventas/listar' => [VentaController::class, 'listar'],
    'ventas/buscar' => [VentaController::class, 'buscar'],
    'ventas/detalles' => [VentaController::class, 'detalles'],
    'perfiles/registrar' => [PerfilController::class, 'registrar'],
    'perfiles/listar' => [PerfilController::class, 'listar'],
    'perfiles/buscar' => [PerfilController::class, 'buscar'],
    'perfiles/actualizar' => [PerfilController::class, 'actualizar'],
    'perfiles/eliminar' => [PerfilController::class, 'eliminar'],
    'usuarios/registrar' => [UsuarioController::class, 'registrar'],
    'usuarios/listar' => [UsuarioController::class, 'listar'],
    'usuarios/buscar' => [UsuarioController::class, 'buscar'],
    'usuarios/actualizar' => [UsuarioController::class, 'actualizar'],
    'usuarios/cambiar-estado' => [UsuarioController::class, 'cambiarEstado'],
    'usuarios/eliminar' => [UsuarioController::class, 'eliminar'],
    'clientes/registrar' => [ClienteController::class, 'registrar'],
    'clientes/listar' => [ClienteController::class, 'listar'],
    'clientes/buscar' => [ClienteController::class, 'buscar'],
    'clientes/buscar-por-dni' => [ClienteController::class, 'buscarPorDni'],
    'proveedores/registrar' => [ProveedorController::class, 'registrar'],
    'proveedores/listar' => [ProveedorController::class, 'listar'],
    'proveedores/buscar' => [ProveedorController::class, 'buscar'],
    'proveedores/actualizar' => [ProveedorController::class, 'actualizar'],
    'proveedores/eliminar' => [ProveedorController::class, 'eliminar'],
    'productos/registrar' => [ProductoController::class, 'registrar'],
    'productos/listar' => [ProductoController::class, 'listar'],
    'productos/actualizar' => [ProductoController::class, 'actualizar'],
    'productos/eliminar' => [ProductoController::class, 'eliminar'],
    'productos/buscar' => [ProductoController::class, 'buscar'],
    'compras/registrar' => [CompraController::class, 'registrar'],
    'compras/listar' => [CompraController::class, 'listar'],
    'compras/buscar' => [CompraController::class, 'buscar'],
    'compras/actualizar-estado' => [CompraController::class, 'actualizarEstado'],
    'inventario/productos' => [InventarioController::class, 'listarProductos'],
    'inventario/producto' => [InventarioController::class, 'buscarProducto'],
    'mesas/registrar' => [MesaController::class, 'registrar'],
    'mesas/listar' => [MesaController::class, 'listar'],
    'mesas/buscar' => [MesaController::class, 'buscar'],
    'mesas/actualizar-estado' => [MesaController::class, 'actualizarEstado'],
    'pedidos/registrar' => [PedidoController::class, 'registrar'],
    'pedidos/listar' => [PedidoController::class, 'listar'],
    'pedidos/listar-por-cliente' => [PedidoController::class, 'listarPorCliente'],
    'pedidos/buscar' => [PedidoController::class, 'buscar'],
    'pedidos/actualizar-estado' => [PedidoController::class, 'actualizarEstado'],
    'pedidos/eliminar' => [PedidoController::class, 'eliminar'],
    'platos/registrar' => [PlatoController::class, 'registrar'],
    'platos/actualizar' => [PlatoController::class, 'actualizar'],
    'platos/subir-imagen' => [PlatoController::class, 'subirImagen'],
    'platos/listar' => [PlatoController::class, 'listar'],
    'platos/buscar' => [PlatoController::class, 'buscar'],
    'caja/abrir' => [CajaController::class, 'abrir'],
    'caja/listar' => [CajaController::class, 'listar'],
    'caja/abierta' => [CajaController::class, 'abierta'],
    'caja/cerrar' => [CajaController::class, 'cerrar'],
    'promociones/registrar' => [PromocionController::class, 'registrar'],
    'promociones/listar' => [PromocionController::class, 'listar'],
    'promociones/actualizar' => [PromocionController::class, 'actualizar'],
    'promociones/buscar' => [PromocionController::class, 'buscar'],
    'promociones/eliminar' => [PromocionController::class, 'eliminar'],
    'reportes/ventas-por-periodo' => [ReporteController::class, 'ventasPorPeriodo'],
    'reportes/ventas-por-metodo-pago' => [ReporteController::class, 'ventasPorMetodoPago'],
    'reportes/tendencia-ventas' => [ReporteController::class, 'tendenciaVentas'],
    'reportes/compras-por-periodo' => [ReporteController::class, 'comprasPorPeriodo'],
    'reportes/compras-por-proveedor' => [ReporteController::class, 'comprasPorProveedor'],
    'reportes/estado-compras' => [ReporteController::class, 'estadoCompras'],
    'reportes/inventario-por-categoria' => [ReporteController::class, 'inventarioPorCategoria'],
    'reportes/inventario-por-estado' => [ReporteController::class, 'inventarioPorEstado'],
    'reportes/rotacion-inventario' => [ReporteController::class, 'rotacionInventario'],
    'reportes/clientes-por-periodo' => [ReporteController::class, 'clientesPorPeriodo'],
    'reportes/clientes-por-metodo-pago' => [ReporteController::class, 'clientesPorMetodoPago'],
    'reportes/clientes-por-tipo-pedido' => [ReporteController::class, 'clientesPorTipoPedido'],
    'reportes/resumen-financiero' => [ReporteController::class, 'resumenFinanciero'],
    'reportes/flujo-caja' => [ReporteController::class, 'flujoCaja'],
    'reportes/gastos-operacionales' => [ReporteController::class, 'gastosOperacionales'],
];
