<?php
require_once __DIR__ . '/controllers/AuthController.php';
require_once __DIR__ . '/controllers/VentaController.php';
require_once __DIR__ . '/controllers/PerfilController.php';
require_once __DIR__ . '/controllers/UsuarioController.php';
require_once __DIR__ . '/controllers/ClienteController.php';
require_once __DIR__ . '/controllers/ProveedorController.php';
require_once __DIR__ . '/controllers/ProductoController.php';
require_once __DIR__ . '/controllers/CompraController.php';
require_once __DIR__ . '/controllers/InventarioController.php';
require_once __DIR__ . '/controllers/InsumoController.php';
require_once __DIR__ . '/controllers/SuministroController.php';
require_once __DIR__ . '/controllers/MesaController.php';
require_once __DIR__ . '/controllers/PedidoController.php';
require_once __DIR__ . '/controllers/PlatoController.php';

return [
    'login' => [AuthController::class, 'login'],
    'ventas/registrar' => [VentaController::class, 'registrar'],
    'perfiles/registrar' => [PerfilController::class, 'registrar'],
    'perfiles/listar' => [PerfilController::class, 'listar'],
    'usuarios/registrar' => [UsuarioController::class, 'registrar'],
    'usuarios/listar' => [UsuarioController::class, 'listar'],
    'clientes/registrar' => [ClienteController::class, 'registrar'],
    'clientes/listar' => [ClienteController::class, 'listar'],
    'clientes/buscar' => [ClienteController::class, 'buscar'],
    'proveedores/registrar' => [ProveedorController::class, 'registrar'],
    'proveedores/listar' => [ProveedorController::class, 'listar'],
    'proveedores/buscar' => [ProveedorController::class, 'buscar'],
    'productos/registrar' => [ProductoController::class, 'registrar'],
    'productos/listar' => [ProductoController::class, 'listar'],
    'productos/actualizar' => [ProductoController::class, 'actualizar'],
    'productos/eliminar' => [ProductoController::class, 'eliminar'],
    'productos/buscar' => [ProductoController::class, 'buscar'],
    'compras/registrar' => [CompraController::class, 'registrar'],
    'compras/listar' => [CompraController::class, 'listar'],
    'compras/buscar' => [CompraController::class, 'buscar'],
    'inventario/productos' => [InventarioController::class, 'listarProductos'],
    'inventario/insumos' => [InventarioController::class, 'listarInsumos'],
    'inventario/suministros' => [InventarioController::class, 'listarSuministros'],
    'inventario/producto' => [InventarioController::class, 'buscarProducto'],
    'inventario/insumo' => [InventarioController::class, 'buscarInsumo'],
    'inventario/suministro' => [InventarioController::class, 'buscarSuministro'],
    'insumos/registrar' => [InsumoController::class, 'registrar'],
    'insumos/listar' => [InsumoController::class, 'listar'],
    'insumos/buscar' => [InsumoController::class, 'buscar'],
    'suministros/registrar' => [SuministroController::class, 'registrar'],
    'suministros/listar' => [SuministroController::class, 'listar'],
    'suministros/buscar' => [SuministroController::class, 'buscar'],
    'mesas/registrar' => [MesaController::class, 'registrar'],
    'mesas/listar' => [MesaController::class, 'listar'],
    'mesas/buscar' => [MesaController::class, 'buscar'],
    'pedidos/registrar' => [PedidoController::class, 'registrar'],
    'pedidos/listar' => [PedidoController::class, 'listar'],
    'pedidos/buscar' => [PedidoController::class, 'buscar'],
    'platos/registrar' => [PlatoController::class, 'registrar'],
    'platos/listar' => [PlatoController::class, 'listar'],
    'platos/buscar' => [PlatoController::class, 'buscar'],
];
